### ISSUE TITLE
Website_support subcategory extra fields still displayed even if category change

### ISSUE THREAD

**Issue by devaqua** [SythilTech/Odoo#12]
Hi, thanks for your quick previous fixes.
I have a new issue with extra fields : 
How to reproduce :
On submit page on website :
- Select a category with a subcategory which have extra fields : Every things are displayed
(This can be the default display when page is loaded)
- Change category to one without subcategory : the subcategory combo-box disappears but extra fields of previous subcategory are still displayed.
Thanks again for your work. Regards

**Comment by devaqua** [comment]
(working with ODOO 10)
This issue is linked with this message in console :

2018-02-27 11:09:29,411 21456 ERROR Aquabio_18_02_13 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 264, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/custom_addons/website_support/controllers/main.py", line 25, in support_subcategories_field_fetch
    sub_category_fields = request.env['website.support.ticket.subcategory.field'].sudo().search( [('wsts_id', '=', int(values['subcategory']) )])
ValueError: invalid literal for int() with base 10: 'undefined'

Handling this error and returning an empty string solve the issue

**Comment by SythilTech** [comment]
Thank you for bringing this issue to my attention, I have released version 1.5.12 which should resolve the issue with extra fields still displaying after category change.
