### ISSUE TITLE
erro install - help

### ISSUE THREAD

**Issue by thiago95macedo** [SythilTech/Odoo#22]
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/adax-erp/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/adax-erp/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/adax-erp/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fcb4f4ddc80>, 'voip_sip_webrtc.model_voip_call')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adax-erp/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adax-erp/odoo/tools/convert.py", line 642, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/adax-erp/odoo/tools/convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/adax-erp/odoo/tools/convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/adax-erp/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_model.py", line 1312, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: voip_sip_webrtc.model_voip_call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adax-erp/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adax-erp/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adax-erp/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adax-erp/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adax-erp/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adax-erp/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adax-erp/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adax-erp/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/adax-erp/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/adax-erp/modulos/interface/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adax-erp/modulos/interface/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adax-erp/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adax-erp/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/adax-erp/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/adax-erp/odoo/modules/loading.py", line 371, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/adax-erp/odoo/modules/loading.py", line 265, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/adax-erp/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/adax-erp/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/adax-erp/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/adax-erp/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/adax-erp/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/opt/adax-erp/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/adax-erp/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/adax-erp/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adax-erp/odoo/tools/convert.py", line 642, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/adax-erp/odoo/tools/convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/adax-erp/odoo/tools/convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/adax-erp/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_model.py", line 1312, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: voip_sip_webrtc.model_voip_call" while parsing /opt/adax-erp/modulos/mail/voip/data/ir.cron.xml:5, near
<record id="clear_messagebank" model="ir.cron">
            <field name="name">Clear Messagebank</field>
            <field name="model_id" ref="voip_sip_webrtc.model_voip_call"/>
            <field name="state">code</field>
            <field name="code">model.clear_messagebank()</field>
            <field name="interval_number">24</field>
            <field name="interval_type">hours</field>
            <field name="numbercall">-1</field>
            <field name="active" eval="True"/>
        </record>

**Comment by SythilTech** [comment]
Hello,

Sorry I am not able to reproduce this issue in my test environment.

Based on the error message it appears to have not created the voip.call model this are generally be causes by a few things.
1. Another module failed to install or upgrade and has been left in the "Cancel install" state
2. Installed modules have been removed from the addons folder before the were uninstalled.

If you can reproduce the error in another database can you please provide additional details about your environment.

Regards
Steven
