### ISSUE TITLE
error after upgrade #voip_sip_webrtc #11.0

### ISSUE THREAD

**Issue by ghost** [SythilTech/Odoo#25]
After upgrading actual-github-version this message:

Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/share/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fc186518d30>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/share/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fc186518940>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/share/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fc186518940>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/share/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/share/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/share/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/share/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/share/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/share/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/share/odoo/odoo/addons/web/controllers/main.py", line 1221, in load
    action = request.env[action_type].browse([action_id]).read()
  File "/usr/share/odoo/3rd-enabled/partner_contact_in_several_companies/models/ir_actions.py", line 12, in read
    actions = super(IRActionsWindow, self).read(fields=fields, load=load)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 198, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/usr/share/odoo/odoo/odoo/models.py", line 2601, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1999, in convert_to_read
    return (value.id, value.sudo().display_name)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/usr/share/odoo/odoo/odoo/models.py", line 1489, in _compute_display_name
    names = dict(self.name_get())
  File "/usr/share/odoo/odoo/odoo/models.py", line 1508, in name_get
    result.append((record.id, convert(record[name], record)))
  File "/usr/share/odoo/odoo/odoo/models.py", line 4754, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/share/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1001, in _compute_value
    self.compute(records)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 586, in _compute_related
    values = [first(value[name]) for value in values]
  File "/usr/share/odoo/odoo/odoo/fields.py", line 586, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/usr/share/odoo/odoo/odoo/models.py", line 4754, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/share/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/share/odoo/odoo/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/usr/share/odoo/odoo/odoo/models.py", line 2646, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/share/odoo/odoo/odoo/addons/base/res/res_users.py", line 921, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/usr/share/odoo/odoo/odoo/addons/base/res/res_users.py", line 307, in read
    result = super(Users, self).read(fields=fields, load=load)
  File "/usr/share/odoo/odoo/odoo/models.py", line 2590, in read
    self._read_from_database(stored, inherited)
  File "/usr/share/odoo/odoo/odoo/models.py", line 2709, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column res_users.voip_presence_status does not exist
LINE 1: SELECT "res_users"."id" as "id","res_users"."voip_presence_s...
                                        ^

**Comment by SythilTech** [comment]
Please ensure you restart your Odoo instance before hitting the upgrade button so the voip_presence_status field is correctly added.

**Comment by ghost** [comment]
i do this:
- odoo shutdown
- git upgarde
- odoo start
-> error message, cant go to upgrade-site

**Comment by aitorbouzas** [comment]
@Axel-G If you can't get to the upgrade screen try to run your odoo instance with this option: `-u voip_sip_webrtc` so that your module updates at the time of starting the odoo.

**Comment by ghost** [comment]
Thank you. Working :)
