### ISSUE TITLE
Error when trying to set Business Hours 

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#37]
Hi Steven,
When in Customer Support --> Settings --> Business Hours, I get this error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/models.py", line 1562, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/opt/odoo/odoo11/odoo/models.py", line 1575, in _name_search
    ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
  File "/opt/odoo/odoo11/odoo/models.py", line 3792, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "_unknown" does not exist
LINE 1: SELECT "_unknown".id FROM "_unknown" ORDER BY "_unknown"."id...
                                  ^
Best regards, Nabeel.

**Comment by SythilTech** [comment]
Thank you for bringing this issue to my attention.

I have released version 1.3.5 for Odoo 11 which adds the resource module to the depend list which that field needs installed.

**Comment by hindsa-nabeel** [comment]
Hi Steven,
Setting Business Hours is working fine now with Version 1.3.5.
Case is now closed.
Best regards, Nabeel.
