### ISSUE TITLE
Website_support : Error when insert Wysiwyg media on ticket creation

### ISSUE THREAD

**Issue by v-garcies** [SythilTech/Odoo#43]
Hi !
I have this error when I save a ticket who have a media in wysiwyg form : 

```
Odoo Server Error

Traceback (most recent call last):
  File "/home/infotelecom/odoo_infotelecom/core/odoo/fields.py", line 331, in __getattr__
    return self._attrs[name]
KeyError: 'ondelete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/infotelecom/odoo_infotelecom/core/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/infotelecom/odoo_infotelecom/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/infotelecom/odoo_infotelecom/core/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/infotelecom/odoo_infotelecom/core/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/infotelecom/odoo_infotelecom/core/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/infotelecom/odoo_infotelecom/addons/website_support/models/website_support_ticket.py", line 363, in write
    update_rec = super(WebsiteSupportTicket, self).write(values)
  File "/home/infotelecom/odoo_infotelecom/core/addons/mail/models/mail_thread.py", line 282, in write
    result = super(MailThread, self).write(values)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/models.py", line 3089, in write
    self._write(old_vals)
  File "/home/infotelecom/odoo_infotelecom/core/odoo/models.py", line 3227, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/home/infotelecom/odoo_infotelecom/core/odoo/fields.py", line 2291, in write
    if inverse_field.ondelete == 'cascade':
  File "/home/infotelecom/odoo_infotelecom/core/odoo/fields.py", line 333, in __getattr__
    raise AttributeError(name)
AttributeError: ondelete
```
Do you have any idea where the problem is coming from?

Thanks in advance !

**Comment by SythilTech** [comment]
Hello thank you for reporting this, unfortunately I was not able to reproduce this in a fresh database, do you perhaps have any modules that make changes to the mail thread? or can you provide any additional details to help me reproduce this error.
