### ISSUE TITLE
fail to submit ticket from website (website_support)

### ISSUE THREAD

**Issue by devaqua** [SythilTech/Odoo#5]
Hi,
sometime i've got this issue but not every time when I click on Submit. Any idea of what could be wrong ?
When I click backward in navigator and then submit again : it works !

EDIT : it seems to append because I was connected as administrator in my dev environment to test the module.

odoo.sql_db: bad query: INSERT INTO "mail_followers" ("id", "res_model", "res_id", "partner_id") VALUES(nextval('mail_followers_id_seq'), 'website.support.ticket', 13, 3) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 591, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo-10.0/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 198, in _dispatch
    return cls.reroute('/'.join(path) or '/')
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 229, in reroute
    return cls._dispatch()
  File "/opt/odoo/odoo-10.0/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 209, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/opt/odoo/odoo-10.0/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo-10.0/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 264, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 141, in wrapper
    raise ValidationError(tr(registry._sql_error[key], 'sql_constraint') or inst[0])
ValidationError: ('Error, a partner cannot follow twice the same object.', None)

**Comment by SythilTech** [comment]
Based on the error it seems to be trying to added the same partner as a mail.follower of the support ticket.

I am unable to reproduce this issue, however I have released version 1.5.10 which removes the automatic administrator follower so this may resolve the issue.

If not can you please provide me with additional details about any settings or modules that you can think would cause this double follower behaviour.

**Comment by devaqua** [comment]
This error didn't occur at each "submit" - I don't have idea how to reproduce it. It seems to be fine on version 1.5.10.
