### ISSUE TITLE
Uninstall module exception: column mail_template.built_in does not exist

### ISSUE THREAD

**Issue by valer9n** [SythilTech/Odoo#6]
Hi,

When trying to uninstall module with created at least a one mail template applies to model 'website.support.ticket' got next exception:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/wizard/base_module_upgrade.py", line 76, in upgrade_module
    odoo.modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 393, in load_modules
    Module.browse(modules_to_remove.values()).module_uninstall()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 425, in module_uninstall
    self.env['ir.model.data']._module_data_uninstall(modules_to_remove)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1360, in _module_data_uninstall
    (datas - undeletable).unlink()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1154, in unlink
    return super(IrModelData, self).unlink()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3442, in unlink
    self.recompute()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5315, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5315, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5211, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 996, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 976, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 969, in _compute_value
    self.compute(records)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 617, in _compute_related
    values = [first(value[name]) for value in values]
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5211, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1012, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3066, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3010, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3134, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column mail_template.built_in does not exist
LINE 1: ...,"mail_template"."ref_ir_value" as "ref_ir_value","mail_temp...
                                                             ^
```
regards

**Comment by SythilTech** [comment]
Hi,

the mail_template.built_in field was added in version 1.4.4, you will need to restart your Odoo service then hit the upgrade button for this field to be added, once the field is adding by upgrading you should be able to uninstall successfully.

**Comment by valer9n** [comment]
Thanks
