### ISSUE TITLE
Kanban view dump in V12

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#68]
Hi Steven,
I faced the below dump when clicking on the View Kanban button. Website Support 12.0.1.0.6 is on Odoo 12 running on a Virtual Machine with CentOS 7.6 and the latest 3.10.0-957.10.1.el7.x86_64 Kernel:
Best Regards, Nabeel.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo12/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo12/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo12/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/models.py", line 2063, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/odoo12/odoo/models.py", line 2091, in _read_group_raw
    annotated_groupbys = [self._read_group_process_groupby(gb, query) for gb in groupby_list]
  File "/opt/odoo/odoo12/odoo/models.py", line 2091, in <listcomp>
    annotated_groupbys = [self._read_group_process_groupby(gb, query) for gb in groupby_list]
  File "/opt/odoo/odoo12/odoo/models.py", line 1896, in _read_group_process_groupby
    field_type = self._fields[split[0]].type
KeyError: 'state'

**Comment by rvalyi** [comment]
Hello. I fixed it in this Pull request: https://github.com/SythilTech/Odoo/pull/70
Also please consider merging https://github.com/SythilTech/Odoo/pull/69 to clean the repo.

**Comment by rvalyi** [comment]
BTW, kudos for the job. I also support the idea of proposing a merge at least of website_support in the OCA. And I can help reviewing the PR or extacting a module.

**Comment by hindsa-nabeel** [comment]
Thanks Raphael.

**Comment by SythilTech** [comment]
Thank you, I'll consider making a PR to OCA after finishing a few things and revising the module a little
