### ISSUE TITLE
Install voip_webrtc_xmpp error !

### ISSUE THREAD

**Issue by mareban** [SythilTech/Odoo#8]
Hello,

I'm trying to install the voip_webrtc_xmpp and got the error below !!

Can someone help me please ?

Thanks.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1228, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 362, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/site-packages/odoo/addons/connector/producer.py", line 30, in create
    record = super(Base, self).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3838, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1000, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/site-packages/odoo/addons/connector/producer.py", line 37, in write
    result = super(Base, self).write(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3564, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3715, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Erreur lors de la validation de la contrainte

L'élément '<field name="voip_account_id">' ne peut être localisé dans la vue parente

Contexte de l'erreur :
Vue `res.users XMPP`
[view_id: 1634, xml_id: n/a, model: res.users, parent_id: 152]
None" while parsing /usr/lib/python2.7/site-packages/odoo/addons/voip_sip_webrtc_xmpp/views/res_users_views.xml:4, near
<record id="view_users_form_inherit_xmpp" model="ir.ui.view">
        <field name="name">res.users XMPP</field>
        <field name="model">res.users</field>
        <field name="inherit_id" ref="base.view_users_form"/>
        <field name="arch" type="xml">
      	    <field name="voip_account_id" position="after">
      	        <field name="xmpp_account_id"/>
      	    </field>
        </field>
    </record>

**Comment by SythilTech** [comment]
Hello,

I have released version 1.0.1 which addresses an install issue related to res_users_views.xml

**Comment by mareban** [comment]
Thanks for your help,

the voip_webrtc_xmmp module is now installed :-) , but how can i select an xmpp account in the compose screen ??

Thx.

**Comment by SythilTech** [comment]
You can setup an XMPP account under the CRM->Voip->XMPP accounts menu, you will be able to select an XMPP account when you go to a contact click on the more menu up the top and select send XMPP message, the functionality under the phone icon all use pure webrtc.

**Comment by mareban** [comment]
Thanks for your help.

Everything is ok now :-).
